/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/models/animated_spiderman_ps5.glb 
*/

import React, { useRef, useEffect } from "react";
import { useFrame } from "@react-three/fiber";
import { useGLTF, useAnimations } from "@react-three/drei";
import { useGameStore } from "./Store";

export function Cube(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("models/cube.glb");
  const { characterState, setCharacterState } = useGameStore((state) => ({
    characterState: state.characterState,
    setCharacterState: state.setCharacterState,
  }));

  const { actions } = useAnimations(animations, group);

  const actionRef = useRef();

  useEffect(() => {
    if (actions[characterState]) {
      actionRef.current = actions[characterState];
      actionRef.current.reset().fadeIn(0.2).play();
    }
    return () => {
      if (actionRef.current) {
        actionRef.current.fadeOut(0.2);
      }
    };
  }, [characterState]);

  //   useFrame(() => {
  //     // console.log(group.current.position);
  //     if (group.current.position.y > 0.1) {
  //       console.log("Hello jumping");
  //       setCharacterState("Jump");
  //     } else if (group.current.position.y < 0) {
  //       console.log("Hello landing");
  //       setCharacterState("Land");
  //     }
  //   });
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Cube.geometry}
        material={nodes.Cube.material}
        position={[0, 0.031, 0]}
        scale={0.13}
      />
    </group>
  );
}

export default Cube;

useGLTF.preload("models/cube.glb");
