/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/models/oscorp_scene.glb 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("models/oscorp_scene.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.LB_Small_Vent_2.geometry}
        material={materials["Dark Gray"]}
        position={[-2.793, -0.01, 0.162]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.037}
      />
      <mesh
        geometry={nodes.LB_Small_Vent_3.geometry}
        material={materials["Dark Gray"]}
        position={[-2.793, -0.01, 0.924]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.037}
      />
      <mesh
        geometry={nodes.LB_Small_Vent_1.geometry}
        material={materials["Dark Gray"]}
        position={[-2.793, -0.01, -0.6]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.037}
      />
      <group
        position={[-4.407, 0.007, 0.814]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.149, 0.004, 0.104]}
      >
        <mesh
          geometry={nodes.Cube083.geometry}
          material={materials["Dark Gray"]}
        />
        <mesh
          geometry={nodes.Cube083_1.geometry}
          material={materials["Darker Gray"]}
        />
      </group>
      <group
        position={[-4.798, 0.007, 0.814]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.149, 0.004, 0.104]}
      >
        <mesh
          geometry={nodes.Cube084.geometry}
          material={materials["Dark Gray"]}
        />
        <mesh
          geometry={nodes.Cube084_1.geometry}
          material={materials["Darker Gray"]}
        />
      </group>
      <group position={[-3.794, -1, -0.164]} rotation={[Math.PI, 0, Math.PI]}>
        <mesh
          geometry={nodes.Cube074.geometry}
          material={materials["Blue Gray 1"]}
        />
        <mesh
          geometry={nodes.Cube074_1.geometry}
          material={materials["Almost Black"]}
        />
        <mesh
          geometry={nodes.Cube074_2.geometry}
          material={materials["Blue Gray 2"]}
        />
      </group>
      <mesh
        geometry={nodes.LB_Wire.geometry}
        material={materials.Black}
        position={[-4.751, 0, -0.999]}
        rotation={[-Math.PI, 0.066, 0]}
        scale={[-0.048, -0.014, -0.011]}
      />
      <group
        position={[-4.022, 0.007, -1.242]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.149, 0.004, 0.104]}
      >
        <mesh
          geometry={nodes.Cube105.geometry}
          material={materials["Dark Gray"]}
        />
        <mesh
          geometry={nodes.Cube105_1.geometry}
          material={materials["Darker Gray"]}
        />
      </group>
      <group
        position={[-4.413, 0.007, -1.242]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.149, 0.004, 0.104]}
      >
        <mesh
          geometry={nodes.Cube106.geometry}
          material={materials["Dark Gray"]}
        />
        <mesh
          geometry={nodes.Cube106_1.geometry}
          material={materials["Darker Gray"]}
        />
      </group>
      <group
        position={[-3.242, 0.007, -1.242]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.149, 0.004, 0.104]}
      >
        <mesh
          geometry={nodes.Cube107.geometry}
          material={materials["Dark Gray"]}
        />
        <mesh
          geometry={nodes.Cube107_1.geometry}
          material={materials["Darker Gray"]}
        />
      </group>
      <group
        position={[-3.633, 0.007, -1.242]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.149, 0.004, 0.104]}
      >
        <mesh
          geometry={nodes.Cube108.geometry}
          material={materials["Dark Gray"]}
        />
        <mesh
          geometry={nodes.Cube108_1.geometry}
          material={materials["Darker Gray"]}
        />
      </group>
      <mesh
        geometry={nodes.Plane022.geometry}
        material={materials["Darker Gray"]}
        position={[0.656, 0.006, 1.018]}
        rotation={[0, -0.166, 0]}
        scale={[0.101, 0.099, 0.1]}
      />
      <mesh
        geometry={nodes.Plane023.geometry}
        material={materials["Dirty Beige 2"]}
        position={[-1.147, 0.008, 1.25]}
        rotation={[-Math.PI, 0.246, -Math.PI]}
        scale={[0.059, 0.079, 0.079]}
      />
      <mesh
        geometry={nodes.Plane024.geometry}
        material={materials["Dirty Beige 1"]}
        position={[-1.266, 0.003, 1.274]}
        rotation={[-Math.PI, 0.785, -Math.PI]}
        scale={[0.043, 0.059, 0.059]}
      />
      <mesh
        geometry={nodes.Plane025.geometry}
        material={materials["Blue Gray 1"]}
        position={[-0.679, 0.003, 1.242]}
        rotation={[Math.PI, -0.394, Math.PI]}
        scale={[0.063, 0.042, 0.054]}
      />
      <mesh
        geometry={nodes.Plane026.geometry}
        material={materials["Darker Gray"]}
        position={[-1.285, 0.003, 1.048]}
        rotation={[-Math.PI, 1.494, -Math.PI]}
        scale={[0.043, 0.059, 0.059]}
      />
      <mesh
        geometry={nodes.Plane027.geometry}
        material={materials["Darker Gray"]}
        position={[-0.127, 0.003, 1.141]}
        rotation={[Math.PI, -1.45, Math.PI]}
        scale={[0.043, 0.027, 0.075]}
      />
      <mesh
        geometry={nodes.Plane043.geometry}
        material={materials["Darker Gray"]}
        position={[-3.158, 0.006, 0.743]}
        rotation={[0, -0.685, 0]}
        scale={[0.101, 0.099, 0.1]}
      />
      <mesh
        geometry={nodes.Plane044.geometry}
        material={materials["Dirty Beige 2"]}
        position={[-4.84, 0.008, 0.051]}
        rotation={[-Math.PI, 0.765, -Math.PI]}
        scale={[0.059, 0.079, 0.079]}
      />
      <mesh
        geometry={nodes.Plane045.geometry}
        material={materials["Dirty Beige 1"]}
        position={[-4.954, 0.003, 0.014]}
        rotation={[-Math.PI, 1.304, -Math.PI]}
        scale={[0.043, 0.059, 0.059]}
      />
      <mesh
        geometry={nodes.Plane046.geometry}
        material={materials["Blue Gray 1"]}
        position={[-4.428, 0.003, 0.276]}
        rotation={[-Math.PI, 0.124, -Math.PI]}
        scale={[0.063, 0.042, 0.054]}
      />
      <mesh
        geometry={nodes.Plane047.geometry}
        material={materials["Darker Gray"]}
        position={[-3.899, 0.003, 0.462]}
        rotation={[Math.PI, -0.932, Math.PI]}
        scale={[0.043, 0.027, 0.075]}
      />
      <mesh
        geometry={nodes.Plane050.geometry}
        material={materials["Darker Gray"]}
        position={[-5.012, 0.003, 1.059]}
        rotation={[Math.PI, -0.932, Math.PI]}
        scale={[0.043, 0.027, 0.075]}
      />
      <mesh
        geometry={nodes.Plane052.geometry}
        material={materials["Dirty Beige 2"]}
        position={[-4.839, 0.008, 1.076]}
        rotation={[0, -0.813, 0]}
        scale={[0.059, 0.079, 0.079]}
      />
      <mesh
        geometry={nodes.Plane053.geometry}
        material={materials["Dirty Beige 1"]}
        position={[-4.673, 0.003, 1.11]}
        rotation={[0, -1.352, 0]}
        scale={[0.043, 0.059, 0.059]}
      />
      <mesh
        geometry={nodes.Plane048.geometry}
        material={materials["Light Gray"]}
        position={[-3.39, 0.003, 0.559]}
        rotation={[0, 0.122, 0]}
        scale={[0.072, 0.07, 0.071]}
      />
      <mesh
        geometry={nodes.Plane049.geometry}
        material={materials["Blue Gray 1"]}
        position={[-3.937, 0.005, 0.381]}
        rotation={[Math.PI, -0.85, Math.PI]}
        scale={[0.041, 0.027, 0.035]}
      />
      <mesh
        geometry={nodes.Plane051.geometry}
        material={materials["Blue Gray 1"]}
        position={[-5.05, 0.005, 0.978]}
        rotation={[Math.PI, -0.85, Math.PI]}
        scale={[0.041, 0.027, 0.035]}
      />
      <mesh
        geometry={nodes.Plane054.geometry}
        material={materials["Dirty Purple 1"]}
        position={[-2.909, 0.003, -1.288]}
        rotation={[0, -0.575, 0]}
        scale={[0.035, 0.047, 0.047]}
      />
      <mesh
        geometry={nodes.Plane055.geometry}
        material={materials.Black}
        position={[-2.721, 0.003, -1.282]}
        rotation={[0, -0.036, 0]}
        scale={[0.065, 0.087, 0.087]}
      />
      <mesh
        geometry={nodes.Plane056.geometry}
        material={materials.Black}
        position={[-2.544, 0.008, -1.332]}
        rotation={[0, -0.575, 0]}
        scale={[0.043, 0.058, 0.058]}
      />
      <mesh
        geometry={nodes.Plane057.geometry}
        material={materials["Dirty Purple 2"]}
        position={[-2.594, 0.003, -1.082]}
        rotation={[0, 0.604, 0]}
        scale={[0.05, 0.033, 0.043]}
      />
      <mesh
        geometry={nodes.Plane058.geometry}
        material={materials["Dark Gray"]}
        position={[-2.79, 0.006, -1.106]}
        rotation={[0, -1.284, 0]}
        scale={[0.035, 0.047, 0.047]}
      />
      <mesh
        geometry={nodes.RB_Small_Exhaust_2.geometry}
        material={materials["Darker Gray"]}
        position={[4.814, -0.002, 0.981]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[-0.11, -0.008, -0.11]}
      />
      <mesh
        geometry={nodes.RB_Small_Exhaust_1.geometry}
        material={materials["Darker Gray"]}
        position={[4.814, -0.002, 0.314]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[-0.11, -0.008, -0.11]}
      />
      <group position={[4.948, -0.018, -1.163]} scale={[0.094, 0.119, 0.094]}>
        <mesh
          geometry={nodes.Cylinder004.geometry}
          material={materials.Black}
        />
        <mesh
          geometry={nodes.Cylinder004_1.geometry}
          material={materials["Darker Gray"]}
        />
      </group>
      <mesh
        geometry={nodes.RB_Satellite_Tower.geometry}
        material={materials.Black}
        position={[2.784, 0.353, -1.165]}
        rotation={[-Math.PI, 0.991, -Math.PI]}
        scale={[-0.018, -0.11, -0.004]}
      />
      <mesh
        geometry={nodes.RB_Wire.geometry}
        material={materials.Black}
        position={[2.804, 0, -1.109]}
        rotation={[Math.PI, -1.072, 0]}
        scale={[-0.048, -0.014, -0.011]}
      />
      <group
        position={[2.834, -0.306, 0.971]}
        rotation={[0, Math.PI / 2, 0]}
        scale={0.587}
      >
        <mesh
          geometry={nodes.Cube085.geometry}
          material={materials["Dark Gray"]}
        />
        <mesh
          geometry={nodes.Cube085_1.geometry}
          material={materials["Darker Gray"]}
        />
        <mesh
          geometry={nodes.Cube085_2.geometry}
          material={materials["Light Gray"]}
        />
      </group>
      <group
        position={[2.834, -0.306, 0.423]}
        rotation={[0, Math.PI / 2, 0]}
        scale={0.587}
      >
        <mesh
          geometry={nodes.Cube086.geometry}
          material={materials["Dark Gray"]}
        />
        <mesh
          geometry={nodes.Cube086_1.geometry}
          material={materials["Darker Gray"]}
        />
        <mesh
          geometry={nodes.Cube086_2.geometry}
          material={materials["Light Gray"]}
        />
      </group>
      <group position={[3.773, -1, 0]}>
        <mesh
          geometry={nodes.Cube078.geometry}
          material={materials["Blue Gray 1"]}
        />
        <mesh
          geometry={nodes.Cube078_1.geometry}
          material={materials["Almost Black"]}
        />
        <mesh
          geometry={nodes.Cube078_2.geometry}
          material={materials["Blue Gray 2"]}
        />
      </group>
      <mesh
        geometry={nodes.Plane028.geometry}
        material={materials["Darker Gray"]}
        position={[3.416, 0.006, 1.048]}
        rotation={[0, -0.74, 0]}
        scale={[0.101, 0.099, 0.1]}
      />
      <mesh
        geometry={nodes.Plane029.geometry}
        material={materials["Dirty Beige 2"]}
        position={[3.615, 0.003, 0.694]}
        rotation={[0, -0.574, 0]}
        scale={[0.099, 0.133, 0.133]}
      />
      <mesh
        geometry={nodes.Plane035.geometry}
        material={materials["Light Gray"]}
        position={[3.226, 0.003, 0.884]}
        rotation={[0, 0.066, 0]}
        scale={[0.072, 0.07, 0.071]}
      />
      <mesh
        geometry={nodes.Plane036.geometry}
        material={materials["Dirty Beige 2"]}
        position={[4.166, 0.006, 0.826]}
        rotation={[0, 0.066, 0]}
        scale={[0.105, 0.07, 0.091]}
      />
      <mesh
        geometry={nodes.Plane037.geometry}
        material={materials["Dirty Purple 1"]}
        position={[4.267, 0.003, -0.759]}
        rotation={[0, 0.997, 0]}
        scale={[0.059, 0.079, 0.079]}
      />
      <mesh
        geometry={nodes.Plane038.geometry}
        material={materials["Darker Gray"]}
        position={[4.14, 0.003, -0.973]}
        rotation={[0, 0.83, 0]}
        scale={[0.06, 0.059, 0.059]}
      />
      <mesh
        geometry={nodes.Plane039.geometry}
        material={materials["Dirty Beige 1"]}
        position={[4.621, 0.003, -0.509]}
        rotation={[0, -0.251, 0]}
        scale={[0.043, 0.059, 0.059]}
      />
      <mesh
        geometry={nodes.Plane040.geometry}
        material={materials["Dirty Beige 2"]}
        position={[4.023, 0.006, 0.207]}
        rotation={[0, -0.902, 0]}
        scale={[0.105, 0.07, 0.091]}
      />
      <mesh
        geometry={nodes.Plane041.geometry}
        material={materials["Dirty Beige 2"]}
        position={[3.607, 0.003, -0.576]}
        rotation={[0, -0.574, 0]}
        scale={[0.063, 0.085, 0.085]}
      />
      <mesh
        geometry={nodes.Plane042.geometry}
        material={materials["Dirty Beige 2"]}
        position={[3.551, 0.006, 0.94]}
        rotation={[0, -0.574, 0]}
        scale={[0.051, 0.069, 0.069]}
      />
      <group position={[0, -1, 0]}>
        <mesh
          geometry={nodes.Cube002.geometry}
          material={materials["Blue Gray 1"]}
        />
        <mesh
          geometry={nodes.Cube002_1.geometry}
          material={materials["Almost Black"]}
        />
        <mesh
          geometry={nodes.Cube002_2.geometry}
          material={materials["Blue Gray 2"]}
        />
      </group>
      <group
        position={[-0.844, -0.306, -0.973]}
        rotation={[0, Math.PI / 2, 0]}
        scale={0.587}
      >
        <mesh
          geometry={nodes.Cube012.geometry}
          material={materials["Dark Gray"]}
        />
        <mesh
          geometry={nodes.Cube012_1.geometry}
          material={materials["Darker Gray"]}
        />
        <mesh
          geometry={nodes.Cube012_2.geometry}
          material={materials["Light Gray"]}
        />
      </group>
      <group
        position={[-0.844, -0.306, 0.971]}
        rotation={[0, Math.PI / 2, 0]}
        scale={0.587}
      >
        <mesh
          geometry={nodes.Cube013.geometry}
          material={materials["Dark Gray"]}
        />
        <mesh
          geometry={nodes.Cube013_1.geometry}
          material={materials["Darker Gray"]}
        />
        <mesh
          geometry={nodes.Cube013_2.geometry}
          material={materials["Light Gray"]}
        />
      </group>
      <mesh
        geometry={nodes.MB_Small_Vent_1.geometry}
        material={materials["Dark Gray"]}
        position={[1, 0, -1]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.037}
      />
      <mesh
        geometry={nodes.MB_Small_Vent_3.geometry}
        material={materials["Darker Gray"]}
        position={[1, 0, 1]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.037}
      />
      <mesh
        geometry={nodes.MB_Wire_2.geometry}
        material={materials.Black}
        position={[0.319, 0, 0.474]}
        scale={[0.048, 0.014, 0.011]}
      />
      <mesh
        geometry={nodes.MB_Wire_1.geometry}
        material={materials.Black}
        position={[0.555, 0, 0.11]}
        rotation={[Math.PI, -1.072, 0]}
        scale={[-0.048, -0.014, -0.011]}
      />
      <mesh
        geometry={nodes.MB_Small_Vent_2.geometry}
        material={materials["Darker Gray"]}
        position={[1, 0, 0.24]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.037}
      />
      <mesh
        geometry={nodes.Plane.geometry}
        material={materials["Dirty Beige 2"]}
        position={[0.63, 0.003, 0.773]}
        scale={[0.099, 0.133, 0.133]}
      />
      <mesh
        geometry={nodes.Plane001.geometry}
        material={materials["Dirty Beige 1"]}
        position={[0.828, 0.003, 0.734]}
        rotation={[0, -0.539, 0]}
        scale={[0.073, 0.099, 0.099]}
      />
      <mesh
        geometry={nodes.Plane002.geometry}
        material={materials["Darker Gray"]}
        position={[0.656, 0.006, 1.018]}
        rotation={[0, -0.166, 0]}
        scale={[0.101, 0.099, 0.1]}
      />
      <mesh
        geometry={nodes.Plane003.geometry}
        material={materials["Light Gray"]}
        position={[0.363, 0.003, 0.974]}
        rotation={[0, 0.64, 0]}
        scale={[0.072, 0.07, 0.071]}
      />
      <mesh
        geometry={nodes.Plane004.geometry}
        material={materials["Dirty Beige 2"]}
        position={[0.906, 0.006, 0.828]}
        rotation={[0, 0.64, 0]}
        scale={[0.105, 0.07, 0.091]}
      />
      <mesh
        geometry={nodes.Plane005.geometry}
        material={materials["Dirty Purple 1"]}
        position={[0.238, 0.003, -0.703]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.059, 0.079, 0.079]}
      />
      <mesh
        geometry={nodes.Plane006.geometry}
        material={materials["Dirty Purple 1"]}
        position={[0.492, 0.003, -0.768]}
        rotation={[0, 1.032, 0]}
        scale={[0.043, 0.059, 0.059]}
      />
      <mesh
        geometry={nodes.Plane007.geometry}
        material={materials["Darker Gray"]}
        position={[0.166, 0.003, -0.911]}
        rotation={[0, 1.404, 0]}
        scale={[0.06, 0.059, 0.059]}
      />
      <mesh
        geometry={nodes.Plane008.geometry}
        material={materials["Light Gray"]}
        position={[0.697, 0.003, -0.39]}
        rotation={[-Math.PI, 0.93, -Math.PI]}
        scale={[0.043, 0.042, 0.042]}
      />
      <mesh
        geometry={nodes.Plane009.geometry}
        material={materials["Dirty Beige 2"]}
        position={[1.138, 0.003, -0.692]}
        rotation={[-Math.PI, 0.93, -Math.PI]}
        scale={[0.063, 0.042, 0.054]}
      />
      <mesh
        geometry={nodes.Plane010.geometry}
        material={materials["Darker Gray"]}
        position={[0.83, 0.003, -0.383]}
        rotation={[-Math.PI, 1.465, -Math.PI]}
        scale={[0.029, 0.028, 0.029]}
      />
      <mesh
        geometry={nodes.Plane011.geometry}
        material={materials["Dirty Beige 1"]}
        position={[0.822, 0.003, -0.784]}
        rotation={[0, 0.323, 0]}
        scale={[0.043, 0.059, 0.059]}
      />
      <mesh
        geometry={nodes.Plane012.geometry}
        material={materials.Black}
        position={[0.634, 0.003, -1.035]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.059, 0.079, 0.079]}
      />
      <mesh
        geometry={nodes.Plane013.geometry}
        material={materials.Black}
        position={[0.652, 0.009, -1.138]}
        rotation={[0, 1.032, 0]}
        scale={[0.043, 0.059, 0.059]}
      />
      <mesh
        geometry={nodes.Plane014.geometry}
        material={materials["Dirty Purple 2"]}
        position={[0.737, 0.003, -1.174]}
        rotation={[-Math.PI, 0.93, -Math.PI]}
        scale={[0.063, 0.042, 0.054]}
      />
      <mesh
        geometry={nodes.Plane015.geometry}
        material={materials["Dark Gray"]}
        position={[0.68, 0.006, -1.221]}
        rotation={[0, 0.323, 0]}
        scale={[0.043, 0.059, 0.059]}
      />
      <mesh
        geometry={nodes.Plane016.geometry}
        material={materials["Dirty Beige 2"]}
        position={[-1.147, 0.008, 1.25]}
        rotation={[-Math.PI, 0.246, -Math.PI]}
        scale={[0.059, 0.079, 0.079]}
      />
      <mesh
        geometry={nodes.Plane017.geometry}
        material={materials["Dirty Beige 1"]}
        position={[-1.266, 0.003, 1.274]}
        rotation={[-Math.PI, 0.785, -Math.PI]}
        scale={[0.043, 0.059, 0.059]}
      />
      <mesh
        geometry={nodes.Plane018.geometry}
        material={materials["Blue Gray 1"]}
        position={[-0.679, 0.003, 1.242]}
        rotation={[Math.PI, -0.394, Math.PI]}
        scale={[0.063, 0.042, 0.054]}
      />
      <mesh
        geometry={nodes.Plane019.geometry}
        material={materials["Darker Gray"]}
        position={[-1.285, 0.003, 1.048]}
        rotation={[-Math.PI, 1.494, -Math.PI]}
        scale={[0.043, 0.059, 0.059]}
      />
      <mesh
        geometry={nodes.Plane020.geometry}
        material={materials["Blue Gray 1"]}
        position={[-0.2, 0.005, 1.089]}
        rotation={[Math.PI, -1.368, Math.PI]}
        scale={[0.041, 0.027, 0.035]}
      />
      <mesh
        geometry={nodes.Plane021.geometry}
        material={materials["Darker Gray"]}
        position={[-0.127, 0.003, 1.141]}
        rotation={[Math.PI, -1.45, Math.PI]}
        scale={[0.043, 0.027, 0.075]}
      />
      <mesh
        geometry={nodes.Plane030.geometry}
        material={materials["Light Gray"]}
        position={[-3.096, -0.061, 0.61]}
        rotation={[-Math.PI, 0.93, -Math.PI]}
        scale={[0.043, 0.042, 0.042]}
      />
      <mesh
        geometry={nodes.Plane031.geometry}
        material={materials["Dirty Beige 1"]}
        position={[-2.971, -0.061, 0.216]}
        rotation={[0, 0.323, 0]}
        scale={[0.043, 0.059, 0.059]}
      />
      <mesh
        geometry={nodes.Plane032.geometry}
        material={materials.Black}
        position={[2.919, -0.06, -0.801]}
        rotation={[-Math.PI, 1.268, -Math.PI]}
        scale={[0.059, 0.079, 0.079]}
      />
      <mesh
        geometry={nodes.Plane033.geometry}
        material={materials.Black}
        position={[2.716, -0.054, -0.895]}
        rotation={[0, 1.032, 0]}
        scale={[0.043, 0.059, 0.059]}
      />
      <mesh
        geometry={nodes.Plane034.geometry}
        material={materials["Dark Gray"]}
        position={[2.835, -0.057, -1.064]}
        rotation={[0, 0.323, 0]}
        scale={[0.043, 0.059, 0.059]}
      />
      <mesh
        geometry={nodes.Plane059.geometry}
        material={materials["Dirty Beige 2"]}
        position={[-1.072, 0.003, -0.185]}
        rotation={[0, -0.229, 0]}
        scale={[0.099, 0.133, 0.133]}
      />
      <mesh
        geometry={nodes.Plane060.geometry}
        material={materials["Dirty Beige 1"]}
        position={[-0.938, 0.012, -0.173]}
        rotation={[0, -0.768, 0]}
        scale={[0.073, 0.099, 0.099]}
      />
      <mesh
        geometry={nodes.Plane061.geometry}
        material={materials["Light Gray"]}
        position={[-1.156, 0.003, 0.181]}
        rotation={[0, 0.411, 0]}
        scale={[0.072, 0.07, 0.071]}
      />
      <group position={[-15.603, -11.06, -23.333]} scale={2.035}>
        <mesh
          geometry={nodes.Cube034.geometry}
          material={materials["Blue Gray 1"]}
        />
        <mesh
          geometry={nodes.Cube034_1.geometry}
          material={materials["Almost Black"]}
        />
        <mesh
          geometry={nodes.Cube034_2.geometry}
          material={materials["Blue Gray 2"]}
        />
      </group>
      <group position={[-15.603, -5.909, -30.819]} scale={2.035}>
        <mesh
          geometry={nodes.Cube050.geometry}
          material={materials["Blue Gray 1"]}
        />
        <mesh
          geometry={nodes.Cube050_1.geometry}
          material={materials["Almost Black"]}
        />
        <mesh
          geometry={nodes.Cube050_2.geometry}
          material={materials["Blue Gray 2"]}
        />
      </group>
      <group position={[-8.217, -3.673, -7.681]} scale={1.58}>
        <mesh
          geometry={nodes.Cube088.geometry}
          material={materials["Blue Gray 1"]}
        />
        <mesh
          geometry={nodes.Cube088_1.geometry}
          material={materials["Almost Black"]}
        />
        <mesh
          geometry={nodes.Cube088_2.geometry}
          material={materials["Blue Gray 2"]}
        />
      </group>
      <group position={[-23.772, -9.485, -23.275]} scale={2.035}>
        <mesh
          geometry={nodes.Cube089.geometry}
          material={materials["Blue Gray 1"]}
        />
        <mesh
          geometry={nodes.Cube089_1.geometry}
          material={materials["Almost Black"]}
        />
        <mesh
          geometry={nodes.Cube089_2.geometry}
          material={materials["Blue Gray 2"]}
        />
      </group>
      <group position={[-7.309, -1.012, -9.277]} scale={[0.064, 0.017, 0.241]}>
        <mesh
          geometry={nodes.Cube077.geometry}
          material={materials["Dark Gray"]}
        />
        <mesh
          geometry={nodes.Cube077_1.geometry}
          material={materials["Darker Gray"]}
        />
        <mesh geometry={nodes.Cube077_2.geometry} material={materials.Blue} />
        <mesh
          geometry={nodes.Cube077_3.geometry}
          material={materials["Almost Black"]}
        />
        <mesh
          geometry={nodes.Cube077_4.geometry}
          material={materials["Dark Grayer"]}
        />
        <mesh
          geometry={nodes.Cube077_5.geometry}
          material={materials["Blue Gray 1"]}
        />
        <mesh geometry={nodes.Cube077_6.geometry} material={materials.Red} />
        <mesh
          geometry={nodes.Cube077_7.geometry}
          material={materials["Dark Blue"]}
        />
      </group>
      <mesh
        geometry={nodes.Lab_Logo.geometry}
        material={materials["Darker Gray"]}
        position={[-9.193, -1.129, -12.058]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[-0.003, -0.005, -0.007]}
      />
      <mesh
        geometry={nodes.Plane062.geometry}
        material={materials["Darker Gray"]}
        position={[-8.735, -2.082, -5.815]}
        rotation={[0, -0.166, 0]}
        scale={[0.101, 0.099, 0.1]}
      />
      <mesh
        geometry={nodes.Plane063.geometry}
        material={materials["Dirty Beige 2"]}
        position={[-9.945, -2.08, -7.279]}
        rotation={[-Math.PI, 0.246, -Math.PI]}
        scale={[0.059, 0.079, 0.079]}
      />
      <mesh
        geometry={nodes.Plane064.geometry}
        material={materials["Dirty Beige 1"]}
        position={[-10.064, -2.085, -7.255]}
        rotation={[-Math.PI, 0.785, -Math.PI]}
        scale={[0.043, 0.059, 0.059]}
      />
      <mesh
        geometry={nodes.Plane065.geometry}
        material={materials["Darker Gray"]}
        position={[-10.083, -2.085, -7.481]}
        rotation={[-Math.PI, 1.494, -Math.PI]}
        scale={[0.043, 0.059, 0.059]}
      />
      <mesh
        geometry={nodes.Plane066.geometry}
        material={materials["Dirty Beige 2"]}
        position={[-8.761, -2.085, -6.06]}
        scale={[0.099, 0.133, 0.133]}
      />
      <mesh
        geometry={nodes.Plane067.geometry}
        material={materials["Dirty Beige 1"]}
        position={[-8.563, -2.085, -6.099]}
        rotation={[0, -0.539, 0]}
        scale={[0.073, 0.099, 0.099]}
      />
      <mesh
        geometry={nodes.Plane068.geometry}
        material={materials["Dirty Beige 2"]}
        position={[-8.485, -2.082, -6.005]}
        rotation={[0, 0.64, 0]}
        scale={[0.105, 0.07, 0.091]}
      />
      <mesh
        geometry={nodes.Plane069.geometry}
        material={materials["Darker Gray"]}
        position={[-9.225, -2.085, -7.744]}
        rotation={[0, 1.404, 0]}
        scale={[0.06, 0.059, 0.059]}
      />
      <mesh
        geometry={nodes.Plane070.geometry}
        material={materials["Light Gray"]}
        position={[-8.694, -2.085, -7.223]}
        rotation={[-Math.PI, 0.93, -Math.PI]}
        scale={[0.043, 0.042, 0.042]}
      />
      <mesh
        geometry={nodes.Plane071.geometry}
        material={materials["Dirty Beige 1"]}
        position={[-8.569, -2.085, -7.617]}
        rotation={[0, 0.323, 0]}
        scale={[0.043, 0.059, 0.059]}
      />
      <mesh
        geometry={nodes.Plane072.geometry}
        material={materials.Black}
        position={[-8.739, -2.079, -7.971]}
        rotation={[0, 1.032, 0]}
        scale={[0.043, 0.059, 0.059]}
      />
      <mesh
        geometry={nodes.Plane073.geometry}
        material={materials["Dirty Beige 2"]}
        position={[-9.182, -2.085, -9.403]}
        rotation={[0, -0.229, 0]}
        scale={[0.099, 0.133, 0.133]}
      />
      <mesh
        geometry={nodes.Plane074.geometry}
        material={materials["Dirty Beige 1"]}
        position={[-9.048, -2.076, -9.39]}
        rotation={[0, -0.768, 0]}
        scale={[0.073, 0.099, 0.099]}
      />
      <mesh
        geometry={nodes.Plane075.geometry}
        material={materials["Light Gray"]}
        position={[-9.266, -2.085, -9.036]}
        rotation={[0, 0.411, 0]}
        scale={[0.072, 0.07, 0.071]}
      />
      <mesh
        geometry={nodes.Plane076.geometry}
        material={materials["Dirty Beige 2"]}
        position={[-8.11, -2.08, -6.642]}
        rotation={[Math.PI, -0.654, Math.PI]}
        scale={[0.059, 0.079, 0.079]}
      />
      <mesh
        geometry={nodes.Plane077.geometry}
        material={materials["Darker Gray"]}
        position={[-8.355, -2.085, -6.659]}
        rotation={[-Math.PI, 0.594, -Math.PI]}
        scale={[0.043, 0.059, 0.059]}
      />
      <mesh
        geometry={nodes.Plane078.geometry}
        material={materials["Dirty Beige 2"]}
        position={[-6.419, -2.085, -6.811]}
        rotation={[0, 0.9, 0]}
        scale={[0.099, 0.133, 0.133]}
      />
      <mesh
        geometry={nodes.Plane079.geometry}
        material={materials["Dirty Beige 2"]}
        position={[-6.205, -2.082, -6.993]}
        rotation={[0, 1.54, 0]}
        scale={[0.105, 0.07, 0.091]}
      />
      <mesh
        geometry={nodes.Plane080.geometry}
        material={materials["Darker Gray"]}
        position={[-8.027, -2.085, -7.495]}
        rotation={[-Math.PI, 0.837, -Math.PI]}
        scale={[0.06, 0.059, 0.059]}
      />
      <mesh
        geometry={nodes.Plane081.geometry}
        material={materials["Light Gray"]}
        position={[-7.288, -2.085, -7.587]}
        rotation={[-Math.PI, 0.031, -Math.PI]}
        scale={[0.043, 0.042, 0.042]}
      />
      <mesh
        geometry={nodes.Plane082.geometry}
        material={materials["Dirty Beige 1"]}
        position={[-7.519, -2.085, -7.93]}
        rotation={[0, 1.223, 0]}
        scale={[0.043, 0.059, 0.059]}
      />
      <mesh
        geometry={nodes.Plane083.geometry}
        material={materials["Dirty Beige 2"]}
        position={[-9.602, -2.085, -7.968]}
        rotation={[0, 0.671, 0]}
        scale={[0.099, 0.133, 0.133]}
      />
      <mesh
        geometry={nodes.Plane084.geometry}
        material={materials["Dirty Beige 1"]}
        position={[-9.51, -2.076, -8.064]}
        rotation={[0, 0.132, 0]}
        scale={[0.073, 0.099, 0.099]}
      />
      <mesh
        geometry={nodes.Plane085.geometry}
        material={materials["Light Gray"]}
        position={[-9.367, -2.085, -7.674]}
        rotation={[0, 1.311, 0]}
        scale={[0.072, 0.07, 0.071]}
      />
      <mesh
        geometry={nodes.Plane086.geometry}
        material={materials["Darker Gray"]}
        position={[-6.6, -2.082, -6.136]}
        rotation={[0, -0.166, 0]}
        scale={[0.101, 0.099, 0.1]}
      />
      <mesh
        geometry={nodes.Plane087.geometry}
        material={materials["Dirty Beige 2"]}
        position={[-7.124, -2.085, -6.102]}
        scale={[0.099, 0.133, 0.133]}
      />
      <mesh
        geometry={nodes.Plane088.geometry}
        material={materials["Dirty Beige 1"]}
        position={[-6.855, -2.085, -6.087]}
        rotation={[0, -0.539, 0]}
        scale={[0.073, 0.099, 0.099]}
      />
      <mesh
        geometry={nodes.Plane089.geometry}
        material={materials["Dirty Beige 2"]}
        position={[-6.729, -2.082, -5.875]}
        rotation={[0, 0.64, 0]}
        scale={[0.105, 0.07, 0.091]}
      />
      <group
        position={[-9.902, -2.394, -9.224]}
        rotation={[0, Math.PI / 2, 0]}
        scale={0.587}
      >
        <mesh
          geometry={nodes.Cube090.geometry}
          material={materials["Dark Gray"]}
        />
        <mesh
          geometry={nodes.Cube090_1.geometry}
          material={materials["Darker Gray"]}
        />
        <mesh
          geometry={nodes.Cube090_2.geometry}
          material={materials["Light Gray"]}
        />
      </group>
      <group
        position={[-9.902, -2.394, -7.807]}
        rotation={[0, Math.PI / 2, 0]}
        scale={0.587}
      >
        <mesh
          geometry={nodes.Cube097.geometry}
          material={materials["Dark Gray"]}
        />
        <mesh
          geometry={nodes.Cube097_1.geometry}
          material={materials["Darker Gray"]}
        />
        <mesh
          geometry={nodes.Cube097_2.geometry}
          material={materials["Light Gray"]}
        />
      </group>
      <group
        position={[-9.902, -2.394, -5.863]}
        rotation={[0, Math.PI / 2, 0]}
        scale={0.587}
      >
        <mesh
          geometry={nodes.Cube091.geometry}
          material={materials["Dark Gray"]}
        />
        <mesh
          geometry={nodes.Cube091_1.geometry}
          material={materials["Darker Gray"]}
        />
        <mesh
          geometry={nodes.Cube091_2.geometry}
          material={materials["Light Gray"]}
        />
      </group>
      <mesh
        geometry={nodes.FLB_Small_Vent_1.geometry}
        material={materials["Dark Gray"]}
        position={[-6.529, -2.088, -7.833]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.037}
      />
      <mesh
        geometry={nodes.FLB_Small_Vent_2.geometry}
        material={materials["Darker Gray"]}
        position={[-6.529, -2.088, -6.593]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.037}
      />
      <mesh
        geometry={nodes.FLB_Small_Vent_3.geometry}
        material={materials["Darker Gray"]}
        position={[-6.529, -2.088, -5.833]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.037}
      />
      <mesh
        geometry={nodes.FLB_Wire_1.geometry}
        material={materials.Black}
        position={[-8.836, -2.088, -6.723]}
        rotation={[Math.PI, -1.072, 0]}
        scale={[-0.048, -0.014, -0.011]}
      />
      <mesh
        geometry={nodes.FLB_Wire_2.geometry}
        material={materials.Black}
        position={[-9.072, -2.088, -6.36]}
        scale={[0.048, 0.014, 0.011]}
      />
      <group position={[10.882, -3.517, -10.768]} scale={1.399}>
        <mesh
          geometry={nodes.Cube048.geometry}
          material={materials["Blue Gray 1"]}
        />
        <mesh
          geometry={nodes.Cube048_1.geometry}
          material={materials["Almost Black"]}
        />
        <mesh
          geometry={nodes.Cube048_2.geometry}
          material={materials["Blue Gray 2"]}
        />
      </group>
      <group position={[13.566, 4.292, -23.333]} scale={2.035}>
        <mesh
          geometry={nodes.Cube049.geometry}
          material={materials["Blue Gray 1"]}
        />
        <mesh
          geometry={nodes.Cube049_1.geometry}
          material={materials["Almost Black"]}
        />
        <mesh
          geometry={nodes.Cube049_2.geometry}
          material={materials["Blue Gray 2"]}
        />
      </group>
      <group position={[9.999, -2.765, -9.861]}>
        <mesh geometry={nodes.Cylinder008.geometry} material={materials.Wood} />
        <mesh
          geometry={nodes.Cylinder008_1.geometry}
          material={materials.Black}
        />
        <mesh
          geometry={nodes.Cylinder008_2.geometry}
          material={materials["Darker Gray"]}
        />
        <mesh
          geometry={nodes.Cylinder008_3.geometry}
          material={materials["Dirty Beige 1"]}
        />
        <mesh
          geometry={nodes.Cylinder008_4.geometry}
          material={materials["Dirty Beige 1.1"]}
        />
      </group>
      <mesh
        geometry={nodes.FRB_Small_Vent_1.geometry}
        material={materials["Dark Gray"]}
        position={[9.332, -2.089, -12.319]}
        rotation={[Math.PI, -Math.PI / 2, 0]}
        scale={-0.037}
      />
      <mesh
        geometry={nodes.FRB_Small_Vent_2.geometry}
        material={materials["Darker Gray"]}
        position={[9.332, -2.089, -11.078]}
        rotation={[Math.PI, -Math.PI / 2, 0]}
        scale={-0.037}
      />
      <mesh
        geometry={nodes.FRB_Small_Vent_3.geometry}
        material={materials["Darker Gray"]}
        position={[9.332, -2.089, -10.319]}
        rotation={[Math.PI, -Math.PI / 2, 0]}
        scale={-0.037}
      />
      <mesh
        geometry={nodes.FRB_Small_Exhaust_1.geometry}
        material={materials["Darker Gray"]}
        position={[12.499, -2.091, -11.004]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[-0.11, -0.008, -0.11]}
      />
      <mesh
        geometry={nodes.FRB_Small_Exhaust_2.geometry}
        material={materials["Darker Gray"]}
        position={[12.499, -2.091, -10.337]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[-0.11, -0.008, -0.11]}
      />
      <mesh
        geometry={nodes.Plane090.geometry}
        material={materials["Darker Gray"]}
        position={[11.315, -2.083, -10.271]}
        rotation={[0, -0.74, 0]}
        scale={[0.101, 0.099, 0.1]}
      />
      <mesh
        geometry={nodes.Plane091.geometry}
        material={materials["Dirty Beige 2"]}
        position={[11.514, -2.086, -10.625]}
        rotation={[0, -0.574, 0]}
        scale={[0.099, 0.133, 0.133]}
      />
      <mesh
        geometry={nodes.Plane092.geometry}
        material={materials["Light Gray"]}
        position={[11.125, -2.086, -10.435]}
        rotation={[0, 0.066, 0]}
        scale={[0.072, 0.07, 0.071]}
      />
      <mesh
        geometry={nodes.Plane093.geometry}
        material={materials["Dirty Beige 2"]}
        position={[12.065, -2.083, -10.492]}
        rotation={[0, 0.066, 0]}
        scale={[0.105, 0.07, 0.091]}
      />
      <mesh
        geometry={nodes.Plane094.geometry}
        material={materials["Dirty Beige 2"]}
        position={[11.922, -2.083, -11.111]}
        rotation={[0, -0.902, 0]}
        scale={[0.105, 0.07, 0.091]}
      />
      <mesh
        geometry={nodes.Plane095.geometry}
        material={materials["Dirty Beige 2"]}
        position={[11.45, -2.083, -10.379]}
        rotation={[0, -0.574, 0]}
        scale={[0.051, 0.069, 0.069]}
      />
      <mesh
        geometry={nodes.Plane096.geometry}
        material={materials["Dirty Beige 2"]}
        position={[9.194, -2.086, -12.01]}
        rotation={[0, 0.93, -Math.PI]}
        scale={[-0.063, -0.042, -0.054]}
      />
      <mesh
        geometry={nodes.Plane097.geometry}
        material={materials["Dirty Beige 1"]}
        position={[9.51, -2.086, -12.102]}
        rotation={[-Math.PI, 0.323, 0]}
        scale={[-0.043, -0.059, -0.059]}
      />
      <group
        position={[-0.256, -2.895, -27.811]}
        rotation={[Math.PI / 2, 0, 0.183]}
        scale={[4.344, 3.865, 14.066]}
      >
        <mesh
          geometry={nodes.Oscorp_Building_Face.geometry}
          material={materials["Almost Black"]}
        />
        <mesh
          geometry={nodes.Oscorp_Building_Face_1.geometry}
          material={materials["Dirty Purple 1"]}
        />
      </group>
      <group
        position={[-4.513, -7.815, -28.924]}
        rotation={[Math.PI / 2, 0, 0.183]}
        scale={[4.344, 3.865, 5.639]}
      >
        <mesh
          geometry={nodes.Oscorp_Building_Face003.geometry}
          material={materials["Almost Black"]}
        />
        <mesh
          geometry={nodes.Oscorp_Building_Face003_1.geometry}
          material={materials["Blue Gray 4"]}
        />
        <mesh
          geometry={nodes.Oscorp_Building_Face003_2.geometry}
          material={materials["Blue Gray 3"]}
        />
      </group>
      <group
        position={[7.771, -7.85, -26.179]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[4.344, 3.865, 5.639]}
      >
        <mesh
          geometry={nodes.Oscorp_Building_Face004.geometry}
          material={materials["Almost Black"]}
        />
        <mesh
          geometry={nodes.Oscorp_Building_Face004_1.geometry}
          material={materials["Blue Gray 4"]}
        />
        <mesh
          geometry={nodes.Oscorp_Building_Face004_2.geometry}
          material={materials["Blue Gray 1"]}
        />
        <mesh
          geometry={nodes.Oscorp_Building_Face004_3.geometry}
          material={materials["Blue Gray 3"]}
        />
      </group>
      <mesh
        geometry={nodes.Lines_Oscorp.geometry}
        material={materials.Black}
        position={[3.482, -12.01, -26.073]}
        scale={[0.135, 19.616, 0.135]}
      />
      <mesh
        geometry={nodes.Oscorp_Logo.geometry}
        material={materials["Oscorp Purple"]}
        position={[-1.253, -3.981, -27.853]}
        rotation={[0, 1.406, Math.PI / 2]}
        scale={[-0.057, -0.108, -0.171]}
      />
      <mesh
        geometry={nodes.LB_Wood_Plank.geometry}
        material={materials["Dirty Beige 1.1"]}
        position={[-2.383, 0.001, -0.081]}
        scale={[0.027, 0.01, 0.165]}
      />
      <mesh
        geometry={nodes.LB_Underlay.geometry}
        material={materials["Dirty Beige 2"]}
        position={[-1.896, -0.011, -0.068]}
        scale={[-0.488, -0.005, -0.155]}
      />
      <mesh
        geometry={nodes.RB_Underlay.geometry}
        material={materials["Dirty Beige 2"]}
        position={[1.897, -0.011, -0.068]}
        scale={[-0.488, -0.005, -0.155]}
      />
      <mesh
        geometry={nodes.RB_Wood_Plank.geometry}
        material={materials["Dirty Beige 1.1"]}
        position={[1.41, 0.001, -0.081]}
        scale={[0.027, 0.01, 0.165]}
      />
    </group>
  );
}

export default Model;

useGLTF.preload("models/oscorp_scene.glb");
