/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/models/animated_spiderman_ps5.glb 
*/

import React, { useRef, useState, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { useGameStore } from "./Store";

export function SpiderManPS5(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "models/animated_spiderman_ps5.glb"
  );
  const characterState = useGameStore((state) => state.characterState);
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    actions[characterState].reset().fadeIn(0.2).play();
    return () => {
      actions[characterState].fadeOut(0.2);
    };
  }, [characterState]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]}>
          <primitive object={nodes.mixamorigHips} />
          <group name="Spider-Man">
            <skinnedMesh
              name="Spider-Man_Redmesh"
              geometry={nodes["Spider-Man_Redmesh"].geometry}
              material={materials.Red}
              skeleton={nodes["Spider-Man_Redmesh"].skeleton}
            />
            <skinnedMesh
              name="Spider-Man_Redmesh_1"
              geometry={nodes["Spider-Man_Redmesh_1"].geometry}
              material={materials.Blue}
              skeleton={nodes["Spider-Man_Redmesh_1"].skeleton}
            />
            <skinnedMesh
              name="Spider-Man_Redmesh_2"
              geometry={nodes["Spider-Man_Redmesh_2"].geometry}
              material={materials.Black}
              skeleton={nodes["Spider-Man_Redmesh_2"].skeleton}
            />
            <skinnedMesh
              name="Spider-Man_Redmesh_3"
              geometry={nodes["Spider-Man_Redmesh_3"].geometry}
              material={materials.White}
              skeleton={nodes["Spider-Man_Redmesh_3"].skeleton}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

export default SpiderManPS5;

useGLTF.preload("models/animated_spiderman_ps5.glb");
